### This ordering is borrowed from https://www.reddit.com/r/dndnext/comments/uyb7gr/feats_tier_list/ without any review
### As I playtest, I can tweak it.


[[feats.common]]
name = "grappler"

[[feats.common]]
name = "dungeon delver"

[[feats.common]]
name = "skilled"

[[feats.common]]
name = "spell sniper"

[[feats.common]]
name = "poisoner"

[[feats.common]]
name = "savage attacker"

[[feats.common]]
name = "lightly armored"

[[feats.common]]
name = "skulker"

[[feats.common]]
name = "dualwielder"

[[feats.common]]
name = "fighting initiate"

[[feats.common]]
name = "elemental adept"

[[feats.common]]
name = "defensive duelist"

######

[[feats.uncommon]]
name = "athlete"

[[feats.uncommon]]
name = "charger"

[[feats.uncommon]]
name = "actor"

[[feats.uncommon]]
name = "alert"

[[feats.uncommon]]
name = "resilient"

[[feats.uncommon]]
name = "mager slater"

[[feats.uncommon]]
name = "alert"

[[feats.uncommon]]
name = "actor"

[[feats.uncommon]]
name = "linguist"

[[feats.uncommon]]
name = "keen mind"

[[feats.uncommon]]
name = "chef"

[[feats.uncommon]]
name = "heavy armor master"

[[feats.uncommon]]
name = "dwarven fortitude"

[[feats.uncommon]]
name = "shield master"

[[feats.uncommon]]
name = "dragon hide"

[[feats.uncommon]]
name = "durable"

[[feats.uncommon]]
name = "mobile"

[[feats.uncommon]]
name = "athlete"

[[feats.uncommon]]
name = "medium armor master"

[[feats.uncommon]]
name = "tavern brawler"

[[feats.uncommon]]
name = "weapon master"

[[feats.uncommon]]
name = "prodigy"

[[feats.uncommon]]
name = "heavily armored"

[[feats.uncommon]]
name = "mounted combatant"

[[feats.uncommon]]
name = "moderately armored"

#####

[[feats.rare]]
name = "war caster"

[[feats.rare]]
name = "crusher"

[[feats.rare]]
name = "slasher"

[[feats.rare]]
name = "piercer"

[[feats.rare]]
name = "dragon fear"

[[feats.rare]]
name = "abberant dragonmark"

[[feats.rare]]
name = "magic initiate"

[[feats.rare]]
name = "ritual caster"

[[feats.rare]]
name = "artificer initiate"

[[feats.rare]]
name = "skill expert"

[[feats.rare]]
name = "charger"

[[feats.rare]]
name = "elven accuracy"

[[feats.rare]]
name = "squat nimbleness"

[[feats.rare]]
name = "second chance"

[[feats.rare]]
name = "fade away"

[[feats.rare]]
name = "orcish fury"

[[feats.rare]]
name = "tough"

[[feats.rare]]
name = "eldritch adept"

[[feats.rare]]
name = "metamagic adept"

[[feats.rare]]
name = "martial adept"

[[feats.rare]]
name = "infernal constitution"

[[feats.rare]]
name = "observant"

[[feats.rare]]
name = "fey teleportation"

[[feats.rare]]
name = "flames of phlegethos"

#####

[[feats.epic]]
name = "lucky"

[[feats.epic]]
name = "polearm master"

[[feats.epic]]
name = "drow high magic"

[[feats.epic]]
name = "wood elf magic"

[[feats.epic]]
name = "svirfneblin magic"

[[feats.epic]]
name = "fey touched"

[[feats.epic]]
name = "shadowed touch"

[[feats.epic]]
name = "inspiring leader"

#####

[[feats.legendary]]
name = "crossbow expert"

[[feats.legendary]]
name = "sentinel"

[[feats.legendary]]
name = "great weapon master"

[[feats.legendary]]
name = "sharpshooter"

[[feats.legendary]]
name = "bountiful luck"

[[feats.legendary]]
name = "healer"

[[feats.legendary]]
name = "telekenetic"

[[feats.legendary]]
name = "telpathic"
